version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    command: bash -c "cd src && python parasite/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8080:8000
    env_file:
      - .env
